/* tslint:disable */
/* eslint-disable */
/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { PaginatedMembershipTypeList } from '../models/index';
import { PaginatedMembershipTypeListFromJSON, PaginatedMembershipTypeListToJSON } from '../models/index';

export interface MembershipTypesListRequest {
  limit?: number;
  offset?: number;
}

/**
 *
 */
export class MembershipsApi extends runtime.BaseAPI {
  /**
   */
  async membershipTypesListRaw(
    requestParameters: MembershipTypesListRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PaginatedMembershipTypeList>> {
    const queryParameters: any = {};

    if (requestParameters.limit !== undefined) {
      queryParameters['limit'] = requestParameters.limit;
    }

    if (requestParameters.offset !== undefined) {
      queryParameters['offset'] = requestParameters.offset;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('jwtAuth', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/api/membership_types`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, jsonValue => PaginatedMembershipTypeListFromJSON(jsonValue));
  }

  /**
   */
  async membershipTypesList(
    requestParameters: MembershipTypesListRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PaginatedMembershipTypeList> {
    const response = await this.membershipTypesListRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
