import { MainNavbar } from "@/components/Header/MainNavbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import { Analytics } from "@vercel/analytics/react";
import SessionProvider from "@/SessionProvider";
import { CaptchaProvider } from "@/CaptchaProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <SessionProvider>
          <MainNavbar></MainNavbar>
          {children}
          <Analytics />
          <Footer></Footer>
        </SessionProvider>
      </body>
    </html>
  );
}
