/* tslint:disable */
/* eslint-disable */
/**
 * backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Membership } from './Membership';
import {
    MembershipFromJSON,
    MembershipFromJSONTyped,
    MembershipToJSON,
} from './Membership';

/**
 * 
 * @export
 * @interface PaginatedMembershipList
 */
export interface PaginatedMembershipList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMembershipList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMembershipList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMembershipList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Membership>}
     * @memberof PaginatedMembershipList
     */
    results?: Array<Membership>;
}

/**
 * Check if a given object implements the PaginatedMembershipList interface.
 */
export function instanceOfPaginatedMembershipList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedMembershipListFromJSON(json: any): PaginatedMembershipList {
    return PaginatedMembershipListFromJSONTyped(json, false);
}

export function PaginatedMembershipListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMembershipList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(MembershipFromJSON)),
    };
}

export function PaginatedMembershipListToJSON(value?: PaginatedMembershipList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(MembershipToJSON)),
    };
}

